#!/bin/sh

# config
SRC=$(dirname $(readlink -f "$0"))

. ${SRC}/client-updates.conf

# Edit news.txt
nano "${UPDATES_DIR}"/release/news.txt

# Commit if changed
cd "${UPDATES_DIR}"
git status | grep -q 'news.txt' && { git add release/news.txt; git commit -m 'Updating news.txt' > /dev/null; }
cd - > /dev/null
