#!/bin/sh

#config
SRC=$(dirname $(readlink -f "$0"))

. ${SRC}/client-updates.conf

DIRECTORY="${UPDATES_DIR}/release"
listing=$(mktemp)
IFS='
'
for f in $(tac $DIRECTORY/resources2.txt); do
    file=$(awk '{ print $1; }' <<< $f)
    unzip -l "$DIRECTORY/$file" >> $listing
done

if [ -f "$listing" ]; then
    less "$listing"
fi
rm -f "$listing"
