notifications:
  email:
    on_success: changed
    on_failure: always

sudo: false

addons:
  apt:
    packages:
    - libxml2-utils

install:
  - pushd ..
  - git clone --depth 1 git://github.com/themanaworld/tmw-tools.git tools
  - popd

script:
  - make check
