#!/bin/bash
DIR=${1:-maps}
for MAP in $(ls "$DIR" | grep '\.tmx$' )
do
    echo -n "${MAP%.tmx}:"
    grep '<tileset' "$DIR/$MAP" |
        while read TILESET
        do
            TILESET=${TILESET#*source=\"}
            TILESET=${TILESET%%.tsx\"*}
            TILESET=${TILESET##*/}
            echo -n " $TILESET"
        done
    echo
done
